version: '3.9'

services:
  mariadb:
    container_name: mon-stack-mariadb
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=dev
    volumes:
      - ./.dev/mariadb/data:/var/lib/mysql:rw
    user: mysql
    ports:
      - 3306:3306

  redis:
    container_name: mon-stack-redis
    image: redis:latest
    ports:
      - 6379:6379
