version: '3.9'

services:
  mariadb:
    container_name: mon-stack-mariadb
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=dev
    volumes:
      - ./.dev/mariadb/data:/var/lib/mysql
    ports:
      - 3306:3306